extends Node

#Acoes
const ACAO = "ACAO_ID_0"
const ACAO_MOVER = "ACAO_MOVER"
const ACAO_MSG = "ACAO_MSG"

#Eventos
const EVENTO = "EVENTO"
const EVENTO_AO_PASSAR="EVENTO_AO_PASSAR"
const EVENTO_MSG_ON_CLICK="EVENTO_MSG_ON_CLICK"
const EVENTO_NPC="EVENTO_NPC"
const EVENTO_COMPLEXO="EVENTO_COMPLEXO"
const EVENTO_AO_TOCAR="EVENTO_AO_TOCAR"

#Opições
const OPTION = "OPTION"
const OPTION_POKEDEX = "OPITION_POKEDEX"
const OPTION_POKEMON = "OPTION_POKEMON"
const OPTION_MOCHILA = "OPTION_MOCHILA"
const OPTION_PERSONAGEM = "OPTION_PERSONAGEM"
const OPTION_SALVAR = "OPTION_SALVAR"
const OPTION_OPTIONS = "OPTION_OPTIONS"
const OPTION_EXIT = "OPTION_EXIT"

#Personagens
const PERSONAGEM = "PERSONAGEM"
const PERSONAGEM_RED = "PERSONAGEM_RED"

#Atributos
const ATRIBUTO_ATAQUE = "ATRIBUTO_ATAQUE"
const ATRIBUTO_ESPECIAL_ATAQUE = "ATRIBUTO_ESPECIAL_ATAQUE"
const ATRIBUTO_DEFESA = "ATRIBUTO_DEFESA"
const ATRIBUTO_ESPECIAL_DEFESA = "ATRIBUTO_ESPECIAL_DEFESA"
const ATRIBUTO_VELOCIDADE = "ATRIBUTO_VELOCIDADE"
const ATRIBUTO_VIDA = "ATRIBUTO_VIDA"

#Caracteristicas
const CARACTERISTICA_FORCA = "CARACTERISTICA_FORCA"
const CARACTERISTICA_RESISTENCIA = "CARACTERISTICA_RESISTENCIA"
const CARACTERISTICA_ELEMENTO = "CARACTERISTICA_ELEMENTO"
const CARACTERISTICA_MENTE = "CARACTERISTICA_MENTE"
const CARACTERISTICA_ACELERACAO = "CARACTERISTICA_ACELERACAO"
const CARACTERISTICA_MOBILIDADE = "CARACTERISTICA_MOBILIDADE"

const ID_FORCA=0
const ID_RESISTENCIA = 1
const ID_ELEMENTO = 2
const ID_MENTE = 3
const ID_ACELERACAO = 4
const ID_MOBILIDADE = 5
const ID_CLASSE_TAMANHO=6

#Armas

const ARMA_SOCO = "ARMA_SOCO"
const ARMA_CHUTE = "ARMA_CHUTE"
const ARMA_GARRA = "ARMA_GARRA"
const ARMA_PRESA = "ARMA_PRESA"
const ARMA_ESPINHO = "ARMA_ESPINHO"
const ARMA_RABO = "ARMA_RABO"
const ARMA_ASA = "ARMA_ASA"
const ARMA_LINGUA = "ARMA_LINGUA"
const ARMA_GIRO = "ARMA_GIRO"

const ID_SOCO=0
const ID_CHUTE = 1
const ID_GARRA = 2
const ID_PRESA = 3
const ID_ESPINHO = 4
const ID_RABO = 5
const ID_ASA=6
const ID_LINGUA=7
const ID_GIRO=8


#Habilidades
const HABILIDADES = ["ataque", "defesa"]
#Movimentos
const MOVIMENTOS = ["correr", "pular"]

#TIPOS

const TIPO_PEDRA = 5
const TIPO_AGUA = 10
const TIPO_ELETRICO = 12
const TIPO_PLANTA = 11
const TIPO_PSIQUICO = 13
const TIPO_VENENO = 3
const TIPO_FOGO = 9
const TIPO_TERRA = 4
const TIPO_VOADOR = 2
const TIPO_INSETO = 6
const TIPO_NORMAL = 0
const TIPO_FANTASMA = 7
const TIPO_LUTADOR = 1
const TIPO_METAL = 8
const TIPO_GELO = 14
const TIPO_DRAGAO = 15
const TIPO_SOMBRIO = 16

#Natures

const NATURE_HARDY = ["NATURE_HARDY", ATRIBUTO_ATAQUE, ATRIBUTO_ATAQUE]
const NATURE_LONELY = ["NATURE_LONELY", ATRIBUTO_ATAQUE, ATRIBUTO_DEFESA]
const NATURE_BRAVE = ["NATURE_BRAVE", ATRIBUTO_ATAQUE, ATRIBUTO_VELOCIDADE]
const NATURE_ADAMANT = ["NATURE_ADAMANT", ATRIBUTO_ATAQUE, ATRIBUTO_ESPECIAL_ATAQUE]
const NATURE_NAUGHTY = ["NATURE_NAUGHTY", ATRIBUTO_ATAQUE, ATRIBUTO_ESPECIAL_DEFESA]
const NATURE_BOLD = ["NATURE_BOLD", ATRIBUTO_DEFESA, ATRIBUTO_ATAQUE]
const NATURE_DOCILE = ["NATURE_DOCILE", ATRIBUTO_DEFESA, ATRIBUTO_DEFESA]
const NATURE_RELAXED = ["NATURE_RELAXED", ATRIBUTO_DEFESA, ATRIBUTO_VELOCIDADE]
const NATURE_IMPISH = ["NATURE_IMPISH", ATRIBUTO_DEFESA, ATRIBUTO_ESPECIAL_ATAQUE]
const NATURE_LAX = ["NATURE_LAX", ATRIBUTO_DEFESA, ATRIBUTO_ESPECIAL_DEFESA]
const NATURE_TIMID = ["NATURE_TIMID", ATRIBUTO_VELOCIDADE, ATRIBUTO_ATAQUE]
const NATURE_HASTY = ["NATURE_HASTY", ATRIBUTO_VELOCIDADE, ATRIBUTO_DEFESA]
const NATURE_SERIOUS = ["NATURE_SERIOUS", ATRIBUTO_VELOCIDADE, ATRIBUTO_VELOCIDADE]
const NATURE_JOLLY = ["NATURE_JOLLY", ATRIBUTO_VELOCIDADE, ATRIBUTO_ESPECIAL_ATAQUE]
const NATURE_NAIVE = ["NATURE_NAIVE", ATRIBUTO_VELOCIDADE, ATRIBUTO_ESPECIAL_DEFESA]
const NATURE_MODEST = ["NATURE_MODEST", ATRIBUTO_ESPECIAL_ATAQUE, ATRIBUTO_ATAQUE]
const NATURE_MILD = ["NATURE_MILD", ATRIBUTO_ESPECIAL_ATAQUE, ATRIBUTO_DEFESA]
const NATURE_QUIET = ["NATURE_QUIET", ATRIBUTO_ESPECIAL_ATAQUE, ATRIBUTO_VELOCIDADE]
const NATURE_BASHFUL = ["NATURE_BASHFUL", ATRIBUTO_ESPECIAL_ATAQUE, ATRIBUTO_ESPECIAL_ATAQUE]
const NATURE_RASH = ["NATURE_RASH", ATRIBUTO_ESPECIAL_ATAQUE, ATRIBUTO_ESPECIAL_DEFESA]
const NATURE_CALM = ["NATURE_CALM", ATRIBUTO_ESPECIAL_DEFESA, ATRIBUTO_ATAQUE]
const NATURE_GENTLE = ["NATURE_GENTLE", ATRIBUTO_ESPECIAL_DEFESA, ATRIBUTO_DEFESA]
const NATURE_SASSY = ["NATURE_SASSY", ATRIBUTO_ESPECIAL_DEFESA, ATRIBUTO_VELOCIDADE]
const NATURE_CAREFUL = ["NATURE_CAREFUL", ATRIBUTO_ESPECIAL_DEFESA, ATRIBUTO_ESPECIAL_ATAQUE]
const NATURE_QUIRKY = ["NATURE_QUIRKY", ATRIBUTO_ESPECIAL_DEFESA, ATRIBUTO_ESPECIAL_DEFESA]
